version: 2
jobs:
 vultr_deploy_fetchsh:
   machine: true
   steps:
 #   - run:
  #       command: |
   #        ssh-keyscan 13.59.53.222 >> ~/.ssh/known_hosts

     - run: |
             sudo apt update && sudo apt install sshpass -y
             export SSHPASS=$USER_PASS1
             sshpass -e ssh ubuntu@13.59.53.222 
workflows:
 version: 2
 rolling_update:
   jobs:
     - vultr_deploy_fetchsh:
         filters:
           branches:
             only:
               - master
