version: 2
- 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git sshpass -y )'
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0
    working_directory: ~/repo
     USER_PASS:SSH_KEY
    steps:
      - checkout
      - run: npm install
      - run: 
    export SSHPASS=$USER_PASS
    sshpass -e ssh ubuntu@13.59.53.222 'ls' 
